name: Welcome message

on: push

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Welcome message
        run: echo "Get the fuck out of here"
      
      - name: List files
        run: ls -la

      - name: Readme content
        run: cat README.md
