name: Generate Cowsay Art

on: push

jobs:
  generate-art:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cowsay
        run: npm install -g cowsay

      - name: Generate art from README
        run: |
          README_CONTENT=$(cat README.md)
          npx cowsay "$README_CONTENT" 